{{- if .Values.mongo.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    {{- include "streamingapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: "mongo"
spec:
  type: ClusterIP
  ports:
    - name: mongodb
      port: {{ .Values.mongo.port }}
      targetPort: mongodb
      protocol: TCP
  selector:
    {{- include "streamingapp.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "mongo"
{{- end }}
